/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.googleanalytics;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

import com.google.analytics.tracking.android.GoogleAnalytics;
import com.google.analytics.tracking.android.Logger.LogLevel;

@Kroll.module(name = "Googleanalytics", id = "ti.googleanalytics")
public class GoogleanalyticsModule extends KrollModule {

	@Kroll.constant public static final int LOG_NONE = 0;
	@Kroll.constant public static final int LOG_ERROR = 1;
	@Kroll.constant public static final int LOG_WARNING = 2;
	@Kroll.constant public static final int LOG_INFO = 3;
	@Kroll.constant public static final int LOG_VERBOSE = 3;
	
	private GoogleAnalytics instance() {
		return GoogleAnalytics.getInstance(TiApplication.getInstance().getApplicationContext());
	}

	@Kroll.method
	public void closeTracker(String trackingId) {
		instance().closeTracker(trackingId);
	}

	@Kroll.method
	@Kroll.getProperty
	public TrackerProxy getDefaultTracker() {
		return new TrackerProxy(instance().getDefaultTracker());
	}

	@Kroll.method
	@Kroll.setProperty
	public void setDefaultTracker(TrackerProxy tracker) {
		instance().setDefaultTracker(tracker.getTracker());
	}

	@Kroll.method
	@Kroll.getProperty
	public TrackerProxy getTracker(String trackingName, String trackingId) {
		return new TrackerProxy(instance().getTracker(trackingName, trackingId));
	}

	@Kroll.method
	@Kroll.getProperty
	public TrackerProxy getTracker(String trackingId) {
		return new TrackerProxy(instance().getTracker(trackingId));
	}

	@Kroll.method
	@Kroll.getProperty
	public boolean getDryRun() {
		return instance().isDryRunEnabled();
	}

	@Kroll.method
	@Kroll.setProperty
	public void setDryRun(boolean dryRun) {
		instance().setDryRun(dryRun);
	}

	@Kroll.method
	@Kroll.getProperty
	public boolean getOptOut() {
		return instance().getAppOptOut();
	}

	@Kroll.method
	@Kroll.setProperty
	public void setOptOut(boolean optOut) {
		instance().setAppOptOut(optOut);
	}

	@Kroll.method
	@Kroll.getProperty
	public MapBuilderProxy getMapBuilder() {
		return new MapBuilderProxy();
	}

	@Kroll.method
	@Kroll.getProperty
	public FieldsProxy getFields() {
		return new FieldsProxy();
	}
	
	private LogLevel convertToLog(int value){
		if(value ==LOG_WARNING){
			return LogLevel.WARNING;			
		}
		if(value ==LOG_INFO){
			return LogLevel.INFO;			
		}			
		if(value ==LOG_VERBOSE){
			return LogLevel.VERBOSE;			
		}		
		return LogLevel.ERROR;
	}

	
	@Kroll.method
	public void setLogLevel(int value)
	{
		instance().getLogger().setLogLevel(convertToLog(value));
	}

}
