/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.googleanalytics;

import java.util.HashMap;
import java.util.Map;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import com.google.analytics.tracking.android.Tracker;

@Kroll.proxy
public class TrackerProxy extends KrollProxy {
	private Tracker _t;

	public TrackerProxy(Tracker tracker) {
		_t = tracker;
	}
	
	public Tracker getTracker() {
		return _t;
	}

	@Kroll.method
	public String get(String key) {
		return _t.get(key);
	}

	@Kroll.method
	public String getName() {
		return _t.getName();
	}

	@Kroll.method
	@SuppressWarnings("rawtypes")
	public void send(HashMap args) {
		Map<String, String> params = new HashMap<String, String>();
		for (Object key : args.keySet()) {
			if (key != null && args.get(key) != null) {
				params.put(key.toString(), args.get(key).toString());
			}
		}
		_t.send(params);
	}

	@Kroll.method
	public void set(String key, String value) {
		_t.set(key, value);
	}

}